---
name: JS Actions

on: [push]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: npm install
      - name: hello-action
        uses: ./.github/actions/hello-world
        with:
          first-greeting: "Learning lab user"
